services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    volumes:
      - ./data:/app/data
    ports:
      - "3001:3001"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.uptime-kuma.rule=Host(`up.ribeiromaier.de`)"
      - "traefik.http.routers.uptime-kuma.entrypoints=websecure"
      - "traefik.http.routers.uptime-kuma.tls.certresolver=leresolver"
      - "traefik.http.services.uptime-kuma.loadbalancer.server.port=3001"
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
    driver: bridge
